### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by markbaltic** [markbaltic/TaborniskaBaza#11]
Zakaj ima header prostor na levi strani? (na desni je vse ok)

**Comment by jaanos** [comment]
V `material.min.css` je za razred `mdl-layout__header-row` določena lastnost `padding: 0 40px 0 80px`, kar pomeni, da bo na levi 80 pikslov prostora, na desni pa le 40. Da bo prostor enakomeren, lahko v svoj CSS dodasta npr.
```css
        .mdl-layout__header-row {
            padding-left: 40px;
        }
```
